### ISSUE TITLE
If uncomment this line then it is showing KeyError

### ISSUE THREAD

**Issue by Saga305** [Saga305/Python#5]
https://github.com/Saga305/Python/blob/551a0fd9e24af74d8c7654bd7022f5482b454e2f/pandas_dataFrame.py#L36

@sagynangare: Could you please help me on this?

**Comment by Saga305** [comment]
dtype: object
Traceback (most recent call last):
  File "test.py", line 36, in <module>
    print (mov[is_long].head())
  File "/usr/lib/python3/dist-packages/pandas/core/frame.py", line 1652, in __getitem__
    return self._getitem_array(key)
  File "/usr/lib/python3/dist-packages/pandas/core/frame.py", line 1696, in _getitem_array
    indexer = self.ix._convert_to_indexer(key, axis=1)
  File "/usr/lib/python3/dist-packages/pandas/core/indexing.py", line 967, in _convert_to_indexer
    raise KeyError('%s not in index' % objarr[mask])

**Comment by Saga305** [comment]
@jorisvandenbossche

Need your help here. Could you please provide some suggestions?

**Comment by Saga305** [comment]
Resolved
